name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - '**'
      - '!*dependabot*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag the docker image
        run: |-
          docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --build-arg BUILD_IMAGE_DOMAIN=${{ vars.GCR_IMAGE_DOMAIN }} \
            --build-arg BUILD_HOSTNAME=${{ vars.GCR_HOSTNAME }} \
            --build-arg BUILD_EMAIL_SERVER_HOST=${{ vars.GCR_EMAIL_SERVER_HOST }} \
            --build-arg BUILD_EMAIL_FROM=${{ vars.GCR_EMAIL_FROM }} \
            --build-arg BUILD_EMAIL_SERVER_PORT=${{ vars.GCR_EMAIL_SERVER_PORT }} \
            --build-arg BUILD_SOCIAL_GITHUB=${{ vars.GCR_SOCIAL_GITHUB }}
      - name: Push docker image
        run: |-
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
