name: Create branch

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        run: |
          git rev-parse new-branch > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Branch already exists"
            exit 0
          fi

      - name: Create branch
        run: |
          git branch new-branch
          git push origin new-branch
